services:
  db:
    image: mongo:8.0
    name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  cache:
    image: redis:7.4
    name: cache
    restart: always
  proxy:
    image: nginx:1.27
    name: proxy
    restart: alway
  api:
    image: 
    name: api
    restart: unless-stopped
  web:
    image:
    name: web
    restart: unless-stopped
